"""add test_quality_score

Revision ID: 006c4ecb08ac
Revises: e2aa8345399e
Create Date: 2026-06-13 12:08:36.690506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006c4ecb08ac'
down_revision: Union[str, None] = 'e2aa8345399e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_tests', sa.Column('test_quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_tests', 'test_quality_score')
    # ### end Alembic commands ###
