"""Add AST fields to Function

Revision ID: 0159579f4427
Revises: 502e9676daef
Create Date: 2026-06-13 12:39:45.467133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0159579f4427'
down_revision: Union[str, None] = '502e9676daef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('start_line', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('end_line', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('functions', sa.Column('docstring', sa.String(), nullable=True))
    op.add_column('functions', sa.Column('function_type', sa.String(), nullable=True))
    op.add_column('functions', sa.Column('is_async', sa.Boolean(), nullable=True))
    op.add_column('functions', sa.Column('return_type', sa.String(), nullable=True))
    op.add_column('functions', sa.Column('decorators', sa.JSON(), nullable=True))
    op.add_column('functions', sa.Column('called_functions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'called_functions')
    op.drop_column('functions', 'decorators')
    op.drop_column('functions', 'return_type')
    op.drop_column('functions', 'is_async')
    op.drop_column('functions', 'function_type')
    op.drop_column('functions', 'docstring')
    op.drop_column('functions', 'parameters')
    op.drop_column('functions', 'end_line')
    op.drop_column('functions', 'start_line')
    # ### end Alembic commands ###
