"""add_dependency_fields

Revision ID: 5005aa6d21cf
Revises: 60f59a2abbba
Create Date: 2026-06-13 11:00:21.431449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5005aa6d21cf'
down_revision: Union[str, None] = '60f59a2abbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('dependency_count', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('impact_radius', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('critical_dependency_score', sa.Float(), nullable=True))
    op.add_column('functions', sa.Column('dependency_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'dependency_level')
    op.drop_column('functions', 'critical_dependency_score')
    op.drop_column('functions', 'impact_radius')
    op.drop_column('functions', 'dependency_count')
    # ### end Alembic commands ###
