"""Add phase 2 columns to Report

Revision ID: 502e9676daef
Revises: 9040c9ea5a43
Create Date: 2026-06-13 12:35:48.879059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502e9676daef'
down_revision: Union[str, None] = '9040c9ea5a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('total_lines', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('covered_lines', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('line_rate', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('branch_rate', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('raw_metrics', sa.JSON(), nullable=True))
    op.drop_column('reports', 'total_functions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('total_functions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'raw_metrics')
    op.drop_column('reports', 'branch_rate')
    op.drop_column('reports', 'line_rate')
    op.drop_column('reports', 'covered_lines')
    op.drop_column('reports', 'total_lines')
    # ### end Alembic commands ###
