"""add_risk_fields

Revision ID: 60f59a2abbba
Revises: 81e376235ef4
Create Date: 2026-06-13 10:52:36.918003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f59a2abbba'
down_revision: Union[str, None] = '81e376235ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    op.add_column('functions', sa.Column('risk_priority_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'risk_priority_rank')
    op.drop_column('functions', 'risk_reasons')
    # ### end Alembic commands ###
