"""Add Function coverage fields

Revision ID: 765dcb33d99e
Revises: 0159579f4427
Create Date: 2026-06-13 12:44:13.455436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765dcb33d99e'
down_revision: Union[str, None] = '0159579f4427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('coverage_percent', sa.Float(), nullable=True))
    op.add_column('functions', sa.Column('executable_lines', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('covered_lines', sa.Integer(), nullable=True))
    op.add_column('functions', sa.Column('coverage_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'coverage_details')
    op.drop_column('functions', 'covered_lines')
    op.drop_column('functions', 'executable_lines')
    op.drop_column('functions', 'coverage_percent')
    # ### end Alembic commands ###
