"""Add GeneratedTest fields

Revision ID: 81e376235ef4
Revises: 765dcb33d99e
Create Date: 2026-06-13 14:39:00.061737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e376235ef4'
down_revision: Union[str, None] = '765dcb33d99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_tests', sa.Column('generation_status', sa.String(), nullable=True))
    op.add_column('generated_tests', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('generated_tests', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_tests', 'generated_at')
    op.drop_column('generated_tests', 'prompt_version')
    op.drop_column('generated_tests', 'generation_status')
    # ### end Alembic commands ###
