"""Update ReportStatus Enum

Revision ID: 9040c9ea5a43
Revises: 2228a029abe6
Create Date: 2026-06-13 12:29:24.863305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9040c9ea5a43'
down_revision: Union[str, None] = '2228a029abe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE reportstatus ADD VALUE IF NOT EXISTS 'ANALYZED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
