"""add_recommendation_category

Revision ID: e2aa8345399e
Revises: 4473d8d4d906
Create Date: 2026-06-13 11:09:36.639798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aa8345399e'
down_revision: Union[str, None] = '4473d8d4d906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('recommendation_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'recommendation_category')
    # ### end Alembic commands ###
